import type { SourceProvider } from '$lib/types';

export const SOURCE_POLICY_URLS: Record<SourceProvider, string> = {
	greenhouse: 'https://developer.greenhouse.io/job-board.html',
	ashby: 'https://developers.ashbyhq.com/docs/public-job-posting-api',
	lever: 'https://github.com/lever/postings-api',
	wwr: 'https://weworkremotely.com/remote-job-rss-feed'
};

export interface CatalogSource {
	provider: SourceProvider;
	name: string;
	boardToken: string;
	policyUrl: string;
}

function catalog(
	provider: SourceProvider,
	companies: ReadonlyArray<readonly [name: string, boardToken: string]>
): CatalogSource[] {
	return companies.map(([name, boardToken]) => ({
		provider,
		name,
		boardToken,
		policyUrl: SOURCE_POLICY_URLS[provider]
	}));
}

// Keep this catalog to sources verified against the provider's public posting endpoint.
// INSERT OR IGNORE migrations add new entries without re-enabling boards a user paused.
export const DEFAULT_SOURCES: CatalogSource[] = [
	...catalog('greenhouse', [
		['Abnormal Security', 'abnormalsecurity'],
		['Adyen', 'adyen'],
		['Affirm', 'affirm'],
		['Airbnb', 'airbnb'],
		['Airtable', 'airtable'],
		['Akuna Capital', 'akunacapital'],
		['Algolia', 'algolia'],
		['Amplitude', 'amplitude'],
		['Anduril', 'andurilindustries'],
		['Anthropic', 'anthropic'],
		['Aptos', 'aptoslabs'],
		['Asana', 'asana'],
		['Automattic', 'automatticcareers'],
		['Aviatrix', 'aviatrix'],
		['BILL', 'billcom'],
		['Blend', 'blend'],
		['Block', 'block'],
		['Braze', 'braze'],
		['Brex', 'brex'],
		['Canonical', 'canonical'],
		['Carta', 'carta'],
		['Chainguard', 'chainguard'],
		['Checkr', 'checkr'],
		['Chime', 'chime'],
		['CircleCI', 'circleci'],
		['Cloudflare', 'cloudflare'],
		['Coalition', 'coalition'],
		['Cockroach Labs', 'cockroachlabs'],
		['Coinbase', 'coinbase'],
		['Consensys', 'consensys'],
		['CoreWeave', 'coreweave'],
		['Coupang', 'coupang'],
		['Coursera', 'coursera'],
		['Cribl', 'cribl'],
		['Databricks', 'databricks'],
		['Datadog', 'datadog'],
		['Dataiku', 'dataiku'],
		['Descript', 'descript'],
		['DigitalOcean', 'digitalocean98'],
		['Discord', 'discord'],
		['DoorDash', 'doordashusa'],
		['Doximity', 'doximity'],
		['Dremio', 'dremio'],
		['Dropbox', 'dropbox'],
		['DRW', 'drweng'],
		['Duolingo', 'duolingo'],
		['EarnIn', 'earnin'],
		['Elastic', 'elastic'],
		['Expel', 'expel'],
		['Faire', 'faire'],
		['Fastly', 'fastly'],
		['Figma', 'figma'],
		['Five Rings', 'fiveringsllc'],
		['Flexport', 'flexport'],
		['Gemini', 'gemini'],
		['GitLab', 'gitlab'],
		['Glean', 'gleanwork'],
		['Grafana Labs', 'grafanalabs'],
		['Gusto', 'gusto'],
		['Harness', 'harnessinc'],
		['Honeycomb', 'honeycomb'],
		['Hudson River Trading', 'wehrtyou'],
		['IMC Trading', 'imc'],
		['Instacart', 'instacart'],
		['Intercom', 'intercom'],
		['Jane Street', 'janestreet'],
		['Jump Trading', 'jumptrading'],
		['Klaviyo', 'klaviyo'],
		['LaunchDarkly', 'launchdarkly'],
		['Lyft', 'lyft'],
		['Mercury', 'mercury'],
		['Mixpanel', 'mixpanel'],
		['MongoDB', 'mongodb'],
		['Motive', 'gomotive'],
		['Netlify', 'netlify'],
		['Netskope', 'netskope'],
		['New Relic', 'newrelic'],
		['Nextdoor', 'nextdoor'],
		['Nuro', 'nuro'],
		['Okta', 'okta'],
		['One Medical', 'onemedical'],
		['OneTrust', 'onetrust'],
		['Optiver', 'optiverus'],
		['Oscar Health', 'oscar'],
		['PagerDuty', 'pagerduty'],
		['Peloton', 'peloton'],
		['Pinterest', 'pinterest'],
		['PlanetScale', 'planetscale'],
		['Point72', 'point72'],
		['Postman', 'postman'],
		['Qualtrics', 'qualtrics'],
		['Reddit', 'reddit'],
		['Reltio', 'reltio'],
		['Remote', 'remotecom'],
		['Ripple', 'ripple'],
		['Robinhood', 'robinhood'],
		['Roblox', 'roblox'],
		['Roku', 'roku'],
		['Rubrik', 'rubrik'],
		['Samsara', 'samsara'],
		['Scale AI', 'scaleai'],
		['SeatGeek', 'seatgeek'],
		['SingleStore', 'singlestore'],
		['Smartsheet', 'smartsheet'],
		['SoFi', 'sofi'],
		['Sourcegraph', 'sourcegraph91'],
		['Squarespace', 'squarespace'],
		['Stripe', 'stripe'],
		['Sumo Logic', 'sumologic'],
		['Tailscale', 'tailscale'],
		['Tanium', 'tanium'],
		['Toast', 'toast'],
		['Together AI', 'togetherai'],
		['Tower Research Capital', 'towerresearchcapital'],
		['Twilio', 'twilio'],
		['Twitch', 'twitch'],
		['Upgrade', 'upgrade'],
		['Upstart', 'upstart'],
		['Vercel', 'vercel'],
		['Verkada', 'verkada'],
		['Virtu Financial', 'virtu'],
		['Waymo', 'waymo'],
		['Webflow', 'webflow'],
		['Wiz', 'wizinc'],
		['WorldQuant', 'worldquant'],
		['Yext', 'yext'],
		['ZipRecruiter', 'ziprecruiter'],
		['Zscaler', 'zscaler']
	]),
	...catalog('ashby', [
		['Abridge', 'abridge'],
		['Alchemy', 'alchemy'],
		['Anrok', 'anrok'],
		['Anyscale', 'anyscale'],
		['Baseten', 'baseten'],
		['Benchling', 'benchling'],
		['Cerebras', 'cerebras'],
		['Character.AI', 'character'],
		['ClickUp', 'clickup'],
		['Cognition', 'cognition'],
		['Cohere', 'cohere'],
		['Crusoe', 'crusoe'],
		['Cursor', 'cursor'],
		['Decagon', 'decagon'],
		['Deepgram', 'deepgram'],
		['Drata', 'drata'],
		['E2B', 'e2b'],
		['ElevenLabs', 'elevenlabs'],
		['Factory', 'factory'],
		['Fireworks AI', 'fireworks'],
		['Harvey', 'harvey'],
		['Hightouch', 'hightouch'],
		['Lambda', 'lambda'],
		['LangChain', 'langchain'],
		['Linear', 'linear'],
		['Liquid AI', 'liquid-ai'],
		['LlamaIndex', 'llamaindex'],
		['Mercor', 'mercor'],
		['Miro', 'miro'],
		['Modal', 'modal'],
		['Modern Treasury', 'moderntreasury'],
		['MotherDuck', 'motherduck'],
		['Notion', 'notion'],
		['OpenAI', 'openai'],
		['Perplexity', 'perplexity'],
		['Pika', 'pika'],
		['Pinecone', 'pinecone'],
		['Plaid', 'plaid'],
		['PostHog', 'posthog'],
		['Prime Intellect', 'primeintellect'],
		['Quora', 'quora'],
		['Railway', 'railway'],
		['Ramp', 'ramp'],
		['Render', 'render'],
		['Replit', 'replit'],
		['Retell AI', 'retell-ai'],
		['Runway', 'runway-ml'],
		['Sierra', 'sierra'],
		['Snowflake', 'snowflake'],
		['Supabase', 'supabase'],
		['Temporal', 'temporal'],
		['Thumbtack', 'thumbtack'],
		['Vanta', 'vanta'],
		['Watershed', 'watershed'],
		['Zapier', 'zapier'],
		['Zip', 'zip']
	]),
	...catalog('lever', [
		['Outreach', 'outreach'],
		['Palantir', 'palantir'],
		['Spotify', 'spotify'],
		['Wealthfront', 'wealthfront'],
		['Zoox', 'zoox']
	]),
	...catalog('wwr', [['We Work Remotely – Engineering', 'remote-engineering']])
];
